# 路径配置 / Path Configuration
function _配置路径 --description "FHS 3.0路径变量"
    set -gx PREFIX "/"
    set -gx BINDIR "$PREFIX/bin"
    set -gx SBINDIR "$PREFIX/sbin"
    set -gx LIBDIR "$PREFIX/lib"
    set -gx LIBEXECDIR "$PREFIX/libexec"
    set -gx INCLUDEDIR "$PREFIX/include"
    set -gx DATAROOTDIR "$PREFIX/share"
    set -gx SYSCONFDIR "$PREFIX/etc"
    set -gx LOCALSTATEDIR "$PREFIX/var"
    set -gx RUNSTATEDIR "$LOCALSTATEDIR/run"
    set -gx SRVDIR "$PREFIX/srv"
    set -gx OPTDIR "$PREFIX/opt"
end